package com.java8.demo.model;

import java.util.Arrays;
import java.util.List;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.logging.Logger;

@Entity
@Table(name = "students")
public class Student {
    // new autogenerated id for JPA

    private static final Logger logger = Logger.getLogger(Student.class.getName());
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "name must not be blank")
    private String name;

    @Min(value = 1, message = "age must be >= 1")
    private int age;

    @NotBlank(message = "gender must not be blank")
    private String gender;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "student_marks", joinColumns = @JoinColumn(name = "student_id"))
    @Column(name = "mark")
    @NotNull(message = "marks must not be null")
    @Size(min = 1, message = "at least one mark is required")
    private List<Integer> marks;

    public Student() {
    }

    public Student(String name, int age, String gender, List<Integer> marks) {
        this.name = name;
        this.age = age;
        this.gender = gender;
        this.marks = marks;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public List<Integer> getMarks() {
        return marks;
    }

    public void setMarks(List<Integer> marks) {
        this.marks = marks;
    }

    public boolean isPass() {

        double avg = marks.stream()
                .mapToInt(Integer::intValue)
                .average()
                .orElse(0);

        logger.info("Student: " + name + " Avg Marks: " + avg);

        return avg >= 35;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", gender='" + gender + '\'' +
                ", marks=" + Arrays.toString(marks == null ? new Integer[0] : marks.toArray(new Integer[0])) +
                '}';
    }
}
